### ISSUE TITLE
Remove the "bikeshed-files" directory, and kill references to it

### ISSUE THREAD

**Issue by tabatkins** [w3c/html#1]
Bikeshed already includes the necessary html include files in its source tree (and has fixed one of them in a way that is not reflected in this repo's stale copy).

That whole directory should be deleted from this repo, and the README instructions altered to remove the reference to it.

**Comment by ZoeBijl** [comment]
Solved in https://github.com/w3c/html/pull/2

**Comment by iandevlin** [comment]
Hmm, would this explain why, after running 'bikeshed -f spec' I get a buttload of fatal errors?

FATAL ERROR: No 'idl' refs found for 'item()' with for='NodeList'.
FATAL ERROR: No 'idl-name' refs found for 'href'.
FATAL ERROR: No 'idl-name' refs found for 'value'.
FATAL ERROR: No 'dfn' refs found for 'selected'.
FATAL ERROR: No 'dfn' refs found for 'caption'.
FATAL ERROR: No 'dfn' refs found for 'seeking'.
FATAL ERROR: No 'dfn' refs found for 'separator'.
FATAL ERROR: No 'dfn' refs found for 'button'.
FATAL ERROR: No 'dfn' refs found for 'ignore' that are marked for export.
FATAL ERROR: No 'method' refs found for 'item()' with for='NodeList'.
FATAL ERROR: No 'dfn' refs found for 'scripting'.
FATAL ERROR: No 'dfn' refs found for 'focus' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'matches' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'abort' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'scripts'.
FATAL ERROR: No 'dfn' refs found for 'marker'.

**Comment by ZoeBijl** [comment]
@iandevlin just tried again on my branch (without the bikeshed-files folder) and I get the same errors. Is it an error in the source? Or did I miss something while installing Bikeshed on OS X 10.10?

**Comment by iandevlin** [comment]
I have no idea where those errors are coming from, I know nothing at all about bikeshed.

**Comment by ZoeBijl** [comment]
Me neither, but I read some of the documentation. And it might be something in the source, because if I use [the API version](https://api.csswg.org/bikeshed/) on single-page.bs in the repo folder:

`curl https://api.csswg.org/bikeshed/ -F file=@single-page.bs -F forece=1 > test.html`

test.html will contain this:

> Error running preprocessor, returned code: 1. [1;31mFATAL ERROR:[0m Couldn't find include file 'sections/introduction.include'. Error was: [Errno 2] No such file or directory: 'sections/introduction.include'

Maybe the references are hooked up wrong?

**Comment by ZoeBijl** [comment]
@iandevlin what OS do you use? I'm on OS X 10.10.5 and did not install anything other than Bikeshed.

**Comment by iandevlin** [comment]
@MichielBijl The same, although I had to install MacPorts too. Everything appears to work though, regardless of the fatal errors.

**Comment by tabatkins** [comment]
It just looks like the conversion isn't quite complete.  Linking errors just make the attempted link _not_ link to anything, so it's a relatively benign failure, tho they should be fixed.

**Comment by adrianba** [comment]
There should only be two errors (see #16).

FATAL ERROR: No 'idl-name' refs found for 'href'.
FATAL ERROR: No 'idl-name' refs found for 'value'.

**Comment by iandevlin** [comment]
Well I just updated to the latest version and am still getting all the errors:

FATAL ERROR: No 'idl' refs found for 'item()' with for='NodeList'.
FATAL ERROR: No 'idl-name' refs found for 'href'.
FATAL ERROR: No 'idl-name' refs found for 'value'.
FATAL ERROR: No 'dfn' refs found for 'selected'.
FATAL ERROR: No 'dfn' refs found for 'caption'.
FATAL ERROR: No 'dfn' refs found for 'seeking'.
FATAL ERROR: No 'dfn' refs found for 'separator'.
FATAL ERROR: No 'dfn' refs found for 'button'.
FATAL ERROR: No 'dfn' refs found for 'ignore' that are marked for export.
FATAL ERROR: No 'method' refs found for 'item()' with for='NodeList'.
FATAL ERROR: No 'dfn' refs found for 'scripting'.
FATAL ERROR: No 'dfn' refs found for 'focus' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'matches' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'abort' that are marked for export.
FATAL ERROR: No 'dfn' refs found for 'scripts'.
FATAL ERROR: No 'dfn' refs found for 'marker'.

**Comment by tabatkins** [comment]
Yes, this is not a Bikeshed bug, it's linking errors in the source.

**Comment by adrianba** [comment]
I had this problem once before and it turned out I really didn't have the latest bikeshed even though I thought I did. Try `git pull -f` in the bikeshed folder and maybe the html folder.

@tabatkins - are you saying tabatkins/bikeshed#559 is not a bug? If so, can you help me figure out what to change in the source? These are the last two errors keeping from building clean.

**Comment by tabatkins** [comment]
Nah, that one's def a bug on my part.

**Comment by iandevlin** [comment]
Ok, thanks for the info.

**Comment by tabatkins** [comment]
And tabatkins/bikeshed#559 is fixed now, so hopefully that's the last of the linking errors in the HTML source.

(A week or two ago it should have stopped erroring, but only because I stopped trying to link the particular thing that was going bad. Now it's fixed for real and should link properly.)
